### ISSUE TITLE
TypeError when load option config

### ISSUE THREAD

**Issue by joe820912boy** [DCsunset/pandoc-include#57] opened 2024-11-05 07:58 UTC
> Traceback (most recent call last):
>   File "/home/jacky/.local/bin/pandoc-include", line 8, in <module>
>     sys.exit(main())
>   File "/home/jacky/.local/lib/python3.8/site-packages/pandoc_include/main.py", line 429, in main
>     return pf.run_filter(action, doc=doc)
>   File "/home/jacky/.local/lib/python3.8/site-packages/panflute/io.py", line 227, in run_filter
>     return run_filters([action], *args, **kwargs)
>   File "/home/jacky/.local/lib/python3.8/site-packages/panflute/io.py", line 208, in run_filters
>     doc = doc.walk(action, doc=doc, stop_if=stop_if)
>   File "/home/jacky/.local/lib/python3.8/site-packages/panflute/base.py", line 264, in walk
>     child = child.walk(action, doc, stop_if)
>   File "/home/jacky/.local/lib/python3.8/site-packages/panflute/base.py", line 272, in walk
>     altered = action(self, doc)
>   File "/home/jacky/.local/lib/python3.8/site-packages/pandoc_include/main.py", line 254, in action
>     options = parseOptions(doc)
>   File "/home/jacky/.local/lib/python3.8/site-packages/pandoc_include/config.py", line 91, in parseOptions
>     options = defaultOptions | json.load(f)
> TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
> Error running filter pandoc-include:
> Filter returned error status 1

I build with pandoc-inlcude and it occurs type error to options config

and my python3 version is Python 3.8.10

**Comment by DCsunset** [comment] 2024-11-07 21:15
Please post the command you use and a minimal document to reproduce the problem. Then it would be easier to locate the error.

**Comment by joe820912boy** [comment] 2024-11-08 02:54
@DCsunset 
```
pandoc --toc --filter ~/.local/bin/pandoc-include --template eisvogel --number-sections --highlight-style tango main.md -o test.pdf
```

and the document i used only empty .md file and it also give the error

**Comment by joe820912boy** [comment] 2024-11-08 09:38
In my .temp.pandoc.include it look likes.

`{"include-entry": {"path": ".", "entered": true}, "current-path": ".", "include-resources": ".", "process-path": "/path/to/md/folder", "include-order": "natural", "rewrite-path": true, "pandoc-options": ["--filter=pandoc-include"]}
`

**Comment by DCsunset** [comment] 2024-11-08 23:08
This seems to be an issue with Python 3.8. I made a fix in the master branch. Can you test it again with your current Python version?

**Comment by joe820912boy** [comment] 2024-11-11 00:54
@DCsunset OK, i will check and give the result

**Comment by joe820912boy** [comment] 2024-11-11 01:39
This master version is worked for me now!!!

Thanks.

**Comment by DCsunset** [comment] 2024-11-11 15:22
This fix is included in v1.4.1. Closing it as completed.

**Closed by DCsunset** 2024-11-11 15:22 UTC
